package com.eycarus.garage.garagecontroller;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GarageControllerMessages.proto

public final class GarageControllerMessages {
    private GarageControllerMessages() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }
    public interface ToggleDoorCommandOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional string SessionId = 1;
        /**
         * <code>optional string SessionId = 1;</code>
         */
        boolean hasSessionId();
        /**
         * <code>optional string SessionId = 1;</code>
         */
        java.lang.String getSessionId();
        /**
         * <code>optional string SessionId = 1;</code>
         */
        com.google.protobuf.ByteString
        getSessionIdBytes();

        // optional int32 DoorNumber = 2 [default = 0];
        /**
         * <code>optional int32 DoorNumber = 2 [default = 0];</code>
         */
        boolean hasDoorNumber();
        /**
         * <code>optional int32 DoorNumber = 2 [default = 0];</code>
         */
        int getDoorNumber();

        // optional int64 Created = 3 [default = 0];
        /**
         * <code>optional int64 Created = 3 [default = 0];</code>
         */
        boolean hasCreated();
        /**
         * <code>optional int64 Created = 3 [default = 0];</code>
         */
        long getCreated();

        // optional int64 Expiry = 4;
        /**
         * <code>optional int64 Expiry = 4;</code>
         */
        boolean hasExpiry();
        /**
         * <code>optional int64 Expiry = 4;</code>
         */
        long getExpiry();

        // optional string Signature = 5;
        /**
         * <code>optional string Signature = 5;</code>
         */
        boolean hasSignature();
        /**
         * <code>optional string Signature = 5;</code>
         */
        java.lang.String getSignature();
        /**
         * <code>optional string Signature = 5;</code>
         */
        com.google.protobuf.ByteString
        getSignatureBytes();
    }
    /**
     * Protobuf type {@code ToggleDoorCommand}
     */
    public static final class ToggleDoorCommand extends
            com.google.protobuf.GeneratedMessage
            implements ToggleDoorCommandOrBuilder {
        // Use ToggleDoorCommand.newBuilder() to construct.
        private ToggleDoorCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private ToggleDoorCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final ToggleDoorCommand defaultInstance;
        public static ToggleDoorCommand getDefaultInstance() {
            return defaultInstance;
        }

        public ToggleDoorCommand getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private ToggleDoorCommand(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            sessionId_ = input.readBytes();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            doorNumber_ = input.readInt32();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            created_ = input.readInt64();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            expiry_ = input.readInt64();
                            break;
                        }
                        case 42: {
                            bitField0_ |= 0x00000010;
                            signature_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return GarageControllerMessages.internal_static_ToggleDoorCommand_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return GarageControllerMessages.internal_static_ToggleDoorCommand_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            GarageControllerMessages.ToggleDoorCommand.class, GarageControllerMessages.ToggleDoorCommand.Builder.class);
        }

        public static com.google.protobuf.Parser<ToggleDoorCommand> PARSER =
                new com.google.protobuf.AbstractParser<ToggleDoorCommand>() {
                    public ToggleDoorCommand parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new ToggleDoorCommand(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<ToggleDoorCommand> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // optional string SessionId = 1;
        public static final int SESSIONID_FIELD_NUMBER = 1;
        private java.lang.Object sessionId_;
        /**
         * <code>optional string SessionId = 1;</code>
         */
        public boolean hasSessionId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string SessionId = 1;</code>
         */
        public java.lang.String getSessionId() {
            java.lang.Object ref = sessionId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    sessionId_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string SessionId = 1;</code>
         */
        public com.google.protobuf.ByteString
        getSessionIdBytes() {
            java.lang.Object ref = sessionId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                sessionId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional int32 DoorNumber = 2 [default = 0];
        public static final int DOORNUMBER_FIELD_NUMBER = 2;
        private int doorNumber_;
        /**
         * <code>optional int32 DoorNumber = 2 [default = 0];</code>
         */
        public boolean hasDoorNumber() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 DoorNumber = 2 [default = 0];</code>
         */
        public int getDoorNumber() {
            return doorNumber_;
        }

        // optional int64 Created = 3 [default = 0];
        public static final int CREATED_FIELD_NUMBER = 3;
        private long created_;
        /**
         * <code>optional int64 Created = 3 [default = 0];</code>
         */
        public boolean hasCreated() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int64 Created = 3 [default = 0];</code>
         */
        public long getCreated() {
            return created_;
        }

        // optional int64 Expiry = 4;
        public static final int EXPIRY_FIELD_NUMBER = 4;
        private long expiry_;
        /**
         * <code>optional int64 Expiry = 4;</code>
         */
        public boolean hasExpiry() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int64 Expiry = 4;</code>
         */
        public long getExpiry() {
            return expiry_;
        }

        // optional string Signature = 5;
        public static final int SIGNATURE_FIELD_NUMBER = 5;
        private java.lang.Object signature_;
        /**
         * <code>optional string Signature = 5;</code>
         */
        public boolean hasSignature() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional string Signature = 5;</code>
         */
        public java.lang.String getSignature() {
            java.lang.Object ref = signature_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    signature_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string Signature = 5;</code>
         */
        public com.google.protobuf.ByteString
        getSignatureBytes() {
            java.lang.Object ref = signature_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                signature_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            sessionId_ = "";
            doorNumber_ = 0;
            created_ = 0L;
            expiry_ = 0L;
            signature_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getSessionIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, doorNumber_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt64(3, created_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt64(4, expiry_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeBytes(5, getSignatureBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getSessionIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, doorNumber_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(3, created_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(4, expiry_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, getSignatureBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static GarageControllerMessages.ToggleDoorCommand parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static GarageControllerMessages.ToggleDoorCommand parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static GarageControllerMessages.ToggleDoorCommand parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static GarageControllerMessages.ToggleDoorCommand parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static GarageControllerMessages.ToggleDoorCommand parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static GarageControllerMessages.ToggleDoorCommand parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static GarageControllerMessages.ToggleDoorCommand parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static GarageControllerMessages.ToggleDoorCommand parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static GarageControllerMessages.ToggleDoorCommand parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static GarageControllerMessages.ToggleDoorCommand parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(GarageControllerMessages.ToggleDoorCommand prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code ToggleDoorCommand}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements GarageControllerMessages.ToggleDoorCommandOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return GarageControllerMessages.internal_static_ToggleDoorCommand_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return GarageControllerMessages.internal_static_ToggleDoorCommand_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                GarageControllerMessages.ToggleDoorCommand.class, GarageControllerMessages.ToggleDoorCommand.Builder.class);
            }

            // Construct using GarageControllerMessages.ToggleDoorCommand.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                sessionId_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                doorNumber_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                created_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000004);
                expiry_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000008);
                signature_ = "";
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return GarageControllerMessages.internal_static_ToggleDoorCommand_descriptor;
            }

            public GarageControllerMessages.ToggleDoorCommand getDefaultInstanceForType() {
                return GarageControllerMessages.ToggleDoorCommand.getDefaultInstance();
            }

            public GarageControllerMessages.ToggleDoorCommand build() {
                GarageControllerMessages.ToggleDoorCommand result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public GarageControllerMessages.ToggleDoorCommand buildPartial() {
                GarageControllerMessages.ToggleDoorCommand result = new GarageControllerMessages.ToggleDoorCommand(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.sessionId_ = sessionId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.doorNumber_ = doorNumber_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.created_ = created_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.expiry_ = expiry_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.signature_ = signature_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof GarageControllerMessages.ToggleDoorCommand) {
                    return mergeFrom((GarageControllerMessages.ToggleDoorCommand)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(GarageControllerMessages.ToggleDoorCommand other) {
                if (other == GarageControllerMessages.ToggleDoorCommand.getDefaultInstance()) return this;
                if (other.hasSessionId()) {
                    bitField0_ |= 0x00000001;
                    sessionId_ = other.sessionId_;
                    onChanged();
                }
                if (other.hasDoorNumber()) {
                    setDoorNumber(other.getDoorNumber());
                }
                if (other.hasCreated()) {
                    setCreated(other.getCreated());
                }
                if (other.hasExpiry()) {
                    setExpiry(other.getExpiry());
                }
                if (other.hasSignature()) {
                    bitField0_ |= 0x00000010;
                    signature_ = other.signature_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                GarageControllerMessages.ToggleDoorCommand parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (GarageControllerMessages.ToggleDoorCommand) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            // optional string SessionId = 1;
            private java.lang.Object sessionId_ = "";
            /**
             * <code>optional string SessionId = 1;</code>
             */
            public boolean hasSessionId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>optional string SessionId = 1;</code>
             */
            public java.lang.String getSessionId() {
                java.lang.Object ref = sessionId_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    sessionId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string SessionId = 1;</code>
             */
            public com.google.protobuf.ByteString
            getSessionIdBytes() {
                java.lang.Object ref = sessionId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    sessionId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string SessionId = 1;</code>
             */
            public Builder setSessionId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                sessionId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string SessionId = 1;</code>
             */
            public Builder clearSessionId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                sessionId_ = getDefaultInstance().getSessionId();
                onChanged();
                return this;
            }
            /**
             * <code>optional string SessionId = 1;</code>
             */
            public Builder setSessionIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                sessionId_ = value;
                onChanged();
                return this;
            }

            // optional int32 DoorNumber = 2 [default = 0];
            private int doorNumber_ ;
            /**
             * <code>optional int32 DoorNumber = 2 [default = 0];</code>
             */
            public boolean hasDoorNumber() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>optional int32 DoorNumber = 2 [default = 0];</code>
             */
            public int getDoorNumber() {
                return doorNumber_;
            }
            /**
             * <code>optional int32 DoorNumber = 2 [default = 0];</code>
             */
            public Builder setDoorNumber(int value) {
                bitField0_ |= 0x00000002;
                doorNumber_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int32 DoorNumber = 2 [default = 0];</code>
             */
            public Builder clearDoorNumber() {
                bitField0_ = (bitField0_ & ~0x00000002);
                doorNumber_ = 0;
                onChanged();
                return this;
            }

            // optional int64 Created = 3 [default = 0];
            private long created_ ;
            /**
             * <code>optional int64 Created = 3 [default = 0];</code>
             */
            public boolean hasCreated() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            /**
             * <code>optional int64 Created = 3 [default = 0];</code>
             */
            public long getCreated() {
                return created_;
            }
            /**
             * <code>optional int64 Created = 3 [default = 0];</code>
             */
            public Builder setCreated(long value) {
                bitField0_ |= 0x00000004;
                created_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int64 Created = 3 [default = 0];</code>
             */
            public Builder clearCreated() {
                bitField0_ = (bitField0_ & ~0x00000004);
                created_ = 0L;
                onChanged();
                return this;
            }

            // optional int64 Expiry = 4;
            private long expiry_ ;
            /**
             * <code>optional int64 Expiry = 4;</code>
             */
            public boolean hasExpiry() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }
            /**
             * <code>optional int64 Expiry = 4;</code>
             */
            public long getExpiry() {
                return expiry_;
            }
            /**
             * <code>optional int64 Expiry = 4;</code>
             */
            public Builder setExpiry(long value) {
                bitField0_ |= 0x00000008;
                expiry_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int64 Expiry = 4;</code>
             */
            public Builder clearExpiry() {
                bitField0_ = (bitField0_ & ~0x00000008);
                expiry_ = 0L;
                onChanged();
                return this;
            }

            // optional string Signature = 5;
            private java.lang.Object signature_ = "";
            /**
             * <code>optional string Signature = 5;</code>
             */
            public boolean hasSignature() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }
            /**
             * <code>optional string Signature = 5;</code>
             */
            public java.lang.String getSignature() {
                java.lang.Object ref = signature_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    signature_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string Signature = 5;</code>
             */
            public com.google.protobuf.ByteString
            getSignatureBytes() {
                java.lang.Object ref = signature_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    signature_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string Signature = 5;</code>
             */
            public Builder setSignature(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                signature_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string Signature = 5;</code>
             */
            public Builder clearSignature() {
                bitField0_ = (bitField0_ & ~0x00000010);
                signature_ = getDefaultInstance().getSignature();
                onChanged();
                return this;
            }
            /**
             * <code>optional string Signature = 5;</code>
             */
            public Builder setSignatureBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                signature_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:ToggleDoorCommand)
        }

        static {
            defaultInstance = new ToggleDoorCommand(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:ToggleDoorCommand)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_ToggleDoorCommand_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_ToggleDoorCommand_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\036GarageControllerMessages.proto\"t\n\021Togg" +
                        "leDoorCommand\022\021\n\tSessionId\030\001 \001(\t\022\025\n\nDoor" +
                        "Number\030\002 \001(\005:\0010\022\022\n\007Created\030\003 \001(\003:\0010\022\016\n\006E" +
                        "xpiry\030\004 \001(\003\022\021\n\tSignature\030\005 \001(\t"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_ToggleDoorCommand_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_ToggleDoorCommand_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_ToggleDoorCommand_descriptor,
                                new java.lang.String[] { "SessionId", "DoorNumber", "Created", "Expiry", "Signature", });
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
